name: Execute Ansible scripts
on: [release]
jobs:
  ansible:
    runs-on: ubuntu-20.04
    # needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Execute ansible playbooks
        uses: ./.github/actions/deploy
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS}}
      - run: echo "üçè This job's status is ${{ job.status }}."
